[PHP]
engine=On
short_open_tag=Off
precision=14
output_buffering=4096
zlib.output_compression=Off
implicit_flush=Off
serialize_precision=-1
zend.enable_gc=On
expose_php=Off
max_execution_time=120
max_input_time=120
memory_limit=512M
error_reporting=E_ALL
display_errors=On
display_startup_errors=On
log_errors=On
post_max_size=32M
upload_max_filesize=32M
default_socket_timeout=60
date.timezone=UTC

extension_dir="C:/Users/apdir/AppData/Local/Microsoft/WinGet/Packages/PHP.PHP.8.2_Microsoft.Winget.Source_8wekyb3d8bbwe/ext"

extension=curl
extension=fileinfo
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=zip

zend_extension=opcache

[opcache]
opcache.enable=1
opcache.enable_cli=1
