<?php

namespace App\Enums;

enum DocumentType: string
{
    case ID_OR_PASSPORT = 'ID_OR_PASSPORT';
    case PASSPORT_PHOTO = 'PASSPORT_PHOTO';
    case CV = 'CV';
    case PAYMENT_PROOF = 'PAYMENT_PROOF';
    case DECLARATION = 'DECLARATION';
    case ENROLLMENT_PROOF = 'ENROLLMENT_PROOF';
    case TRANSCRIPT = 'TRANSCRIPT';
    case DEGREE = 'DEGREE';
    case EXPERIENCE_LETTER = 'EXPERIENCE_LETTER';
    case EMPLOYER_REFERENCE = 'EMPLOYER_REFERENCE';
    case PROJECT_PORTFOLIO = 'PROJECT_PORTFOLIO';
    case REFEREE_ONE = 'REFEREE_ONE';
    case REFEREE_TWO = 'REFEREE_TWO';
    case FELLOW_NOMINATION = 'FELLOW_NOMINATION';
    case ACHIEVEMENT_PROFILE = 'ACHIEVEMENT_PROFILE';
}
